workflows:
  build-ios-app:
    name: Build iOS IPA for MoneyNest
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      groups:
        - ios_credentials
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS .ipa (unsigned)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
