workflows:
  build-ios-app:
    name: Build iOS IPA for MoneyNest
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: "moneynest"
        TEAM_ID: "7GX9J7V725"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build iOS .app (unsigned)
        script: |
          flutter build ios --release --no-codesign

      - name: Create unsigned .ipa
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r MoneyNest.ipa Payload
          rm -rf Payload
    artifacts:
      - MoneyNest.ipa
