workflows:
  build-ios-app:
    name: Build iOS IPA for MoneyNest
    max_build_duration: 30
    environment:
      groups:
        - ios-signing          
      xcode: latest
      vars:
        APP_ID: "moneynest"
        TEAM_ID: "7GX9J7V725"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build iOS .app (signed)
        script: |
          flutter build ios --release

      - name: Create .ipa
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r MoneyNest.ipa Payload

    artifacts:
      - MoneyNest.ipa
      - build/ios/iphoneos/Runner.app
