workflows:
  build-ios-app:
    name: Build iOS IPA for MoneyNest
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: "moneynest"
        TEAM_ID: "7GX9J7V725"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Decode and install signing files
        script: |
          echo $P12_BASE64 | base64 --decode > astinori.p12
          echo $PROFILE_BASE64 | base64 --decode > astinori.mobileprovision

          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "" -T /usr/bin/codesign

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build iOS .app (signed)
        script: |
          flutter build ios --release

      - name: Create .ipa
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r MoneyNest.ipa Payload

    artifacts:
      - MoneyNest.ipa
      - build/ios/iphoneos/Runner.app